' Developer Express Code Central Example:
' How to use automatic date-time scale modes of an axis
' 
' This example demonstrates how to use date-time scale modes of an axis
' (http://devexpress.com/Help/Content.aspx?help=XtraCharts&document=CustomDocument6016.htm)
' (both manual and automatic).
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E1531
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18052
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace DateTimeAggregation.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As DateTimeAggregation.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New DateTimeAggregation.Properties.Settings())), DateTimeAggregation.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return DateTimeAggregation.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
